var city = {
    "11": [
        { laber: "东城" },
        { laber: "西城" },
        { laber: "崇文" },
        { laber: "宣武" },
        { laber: "朝阳" },
        { laber: "丰台" },
        { laber: "石景山" },
        { laber: "海淀" },
        { laber: "门头沟" },
        { laber: "房山" },
        { laber: "通州" },
        { laber: "顺义" },
        { laber: "昌平" },
        { laber: "大兴" },
        { laber: "怀柔" },
        { laber: "平谷" },
        { laber: "密云" },
        { laber: "延庆" }]
    ,
    "12": [
        { laber: "和平区" },
        { laber: "河东区" },
        { laber: "河西区" },
        { laber: "南开区" },
        { laber: "河北区" },
        { laber: "红桥区" },
        { laber: "塘沽区" },
        { laber: "汉沽区" },
        { laber: "大港区" },
        { laber: "东丽区" },
        { laber: "西青区" },
        { laber: "津南区" },
        { laber: "北辰区" },
        { laber: "武清区" },
        { laber: "宝坻区" },
        { laber: "宁河县" },
        { laber: "静海县" },
        { laber: "蓟县" },
        { laber: "滨海新区" },
        { laber: "保税区" }
    ],
    "13": [
        { laber: "石家庄" },
        { laber: "唐山" },
        { laber: "秦皇岛" },
        { laber: "邯郸" },
        { laber: "邢台" },
        { laber: "保定" },
        { laber: "张家口" },
        { laber: "承德" },
        { laber: "沧州" },
        { laber: "廊坊" },
        { laber: "衡水" }
    ],
    "14": [
        { laber: "太原" },
        { laber: "大同" },
        { laber: "阳泉" },
        { laber: "长治" },
        { laber: "晋城" },
        { laber: "朔州" },
        { laber: "晋中" },
        { laber: "运城" },
        { laber: "忻州" },
        { laber: "临汾" },
        { laber: "吕梁" },

    ],
    "15": [{ laber: "呼和浩特" },
    { laber: "包头" },
    { laber: "乌海" },
    { laber: "赤峰" },
    { laber: "通辽" },
    { laber: "鄂尔多斯" },
    { laber: "呼伦贝尔" },
    { laber: "兴安盟" },
    { laber: "锡林郭勒盟" },
    { laber: "乌兰察布盟" },
    { laber: "巴彦淖尔盟" },
    { laber: "阿拉善盟" },
    ],
    "21": [{ laber: "沈阳" },
    { laber: "大连" },
    { laber: "鞍山" },
    { laber: "抚顺" },
    { laber: "本溪" },
    { laber: "丹东" },
    { laber: "锦州" },
    { laber: "营口" },
    { laber: "阜新" },
    { laber: "辽阳" },
    { laber: "盘锦" },
    { laber: "铁岭" },
    { laber: "朝阳" },
    { laber: "葫芦岛" },
    ],
    "22": [{ laber: "长春" },
    { laber: "吉林" },
    { laber: "四平" },
    { laber: "辽源" },
    { laber: "通化" },
    { laber: "白山" },
    { laber: "松原" },
    { laber: "白城" },
    { laber: "延边朝鲜族自治州" },
    ],
    "23": [{ laber: "哈尔滨" },
    { laber: "齐齐哈尔" },
    { laber: "鸡西" },
    { laber: "鹤岗" },
    { laber: "双鸭山" },
    { laber: "大庆" },
    { laber: "伊春" },
    { laber: "佳木斯" },
    { laber: "七台河" },
    { laber: "牡丹江" },
    { laber: "黑河" },
    { laber: "绥化" },
    { laber: "大兴安岭" },
    ],
    "31": [{ laber: "黄浦区" },
    { laber: "卢湾区" },
    { laber: "徐汇区" },
    { laber: "长宁区" },
    { laber: "静安区" },
    { laber: "普陀区" },
    { laber: "闸北区" },
    { laber: "虹口区" },
    { laber: "杨浦区" },
    { laber: "闵行区" },
    { laber: "宝山区" },
    { laber: "嘉定区" },
    { laber: "浦东新区" },
    { laber: "金山区" },
    { laber: "松江区" },
    { laber: "青浦区" },
    { laber: "南汇区" },
    { laber: "奉贤区" },
    { laber: "崇明区" },
    ],
    "32": [{ laber: "南京" },
    { laber: "无锡" },
    { laber: "徐州" },
    { laber: "常州" },
    { laber: "苏州" },
    { laber: "南通" },
    { laber: "连云港" },
    { laber: "淮安" },
    { laber: "盐城" },
    { laber: "扬州" },
    { laber: "镇江" },
    { laber: "泰州" },
    { laber: "宿迁" },
    ],
    "33": [{ laber: "杭州" },
    { laber: "宁波" },
    { laber: "温州" },
    { laber: "嘉兴" },
    { laber: "湖州" },
    { laber: "绍兴" },
    { laber: "金华" },
    { laber: "衢州" },
    { laber: "舟山" },
    { laber: "台州" },
    { laber: "丽水" },
    ],
    "34": [{ laber: "合肥" },
    { laber: "芜湖" },
    { laber: "蚌埠" },
    { laber: "淮南" },
    { laber: "马鞍山" },
    { laber: "淮北" },
    { laber: "铜陵" },
    { laber: "安庆" },
    { laber: "黄山" },
    { laber: "滁州" },
    { laber: "阜阳" },
    { laber: "宿州" },
    { laber: "巢湖" },
    { laber: "六安" },
    { laber: "亳州" },
    { laber: "池州" },
    { laber: "宣城" },
    ],
    "35": [{ laber: "福州" },
    { laber: "厦门" },
    { laber: "莆田" },
    { laber: "三明" },
    { laber: "泉州" },
    { laber: "漳州" },
    { laber: "南平" },
    { laber: "龙岩" },
    { laber: "宁德" },
    ],
    "36": [{ laber: "南昌" },
    { laber: "景德镇" },
    { laber: "萍乡" },
    { laber: "九江" },
    { laber: "新余" },
    { laber: "鹰潭" },
    { laber: "赣州" },
    { laber: "吉安" },
    { laber: "宜春" },
    { laber: "抚州" },
    { laber: "上饶" },
    ],
    "37": [{ laber: "济南" },
    { laber: "青岛" },
    { laber: "淄博" },
    { laber: "枣庄" },
    { laber: "东营" },
    { laber: "烟台" },
    { laber: "潍坊" },
    { laber: "济宁" },
    { laber: "泰安" },
    { laber: "威海" },
    { laber: "日照" },
    { laber: "莱芜" },
    { laber: "临沂" },
    { laber: "德州" },
    { laber: "聊城" },
    { laber: "滨州" },
    { laber: "菏泽" },
    ],
    "41": [{ laber: "郑州" },
    { laber: "开封" },
    { laber: "洛阳" },
    { laber: "平顶山" },
    { laber: "安阳" },
    { laber: "鹤壁" },
    { laber: "新乡" },
    { laber: "焦作" },
    { laber: "濮阳" },
    { laber: "许昌" },
    { laber: "漯河" },
    { laber: "三门峡" },
    { laber: "南阳" },
    { laber: "商丘" },
    { laber: "信阳" },
    { laber: "周口" },
    { laber: "驻马店" },
    { laber: "济源" },
    ],
    "42": [{ laber: "武汉" },
    { laber: "黄石" },
    { laber: "十堰" },
    { laber: "宜昌" },
    { laber: "襄阳" },
    { laber: "鄂州" },
    { laber: "荆门" },
    { laber: "孝感" },
    { laber: "荆州" },
    { laber: "黄冈" },
    { laber: "咸宁" },
    { laber: "随州" },
    { laber: "恩施土家族苗族自治州" },
    { laber: "仙桃" },
    { laber: "潜江" },
    { laber: "天门" },
    { laber: "神农架" },
    ],
    "43": [{ laber: "长沙" },
    { laber: "株洲" },
    { laber: "湘潭" },
    { laber: "衡阳" },
    { laber: "邵阳" },
    { laber: "岳阳" },
    { laber: "常德" },
    { laber: "张家界" },
    { laber: "益阳" },
    { laber: "郴州" },
    { laber: "永州" },
    { laber: "怀化" },
    { laber: "娄底" },
    { laber: "湘西土家族苗族自治州" },
    ],
    "44": [{ laber: "广州" },
    { laber: "韶关" },
    { laber: "深圳" },
    { laber: "珠海" },
    { laber: "汕头" },
    { laber: "佛山" },
    { laber: "江门" },
    { laber: "湛江" },
    { laber: "茂名" },
    { laber: "肇庆" },
    { laber: "惠州" },
    { laber: "梅州" },
    { laber: "汕尾" },
    { laber: "河源" },
    { laber: "阳江" },
    { laber: "清远" },
    { laber: "东莞" },
    { laber: "中山" },
    { laber: "潮州" },
    { laber: "揭阳" },
    { laber: "云浮" },
    ],
    "45": [{ laber: "南宁" },
    { laber: "桂林" },
    { laber: "梧州" },
    { laber: "北海" },
    { laber: "防城港" },
    { laber: "钦州" },
    { laber: "贵港" },
    { laber: "玉林" },
    { laber: "百色" },
    { laber: "贺州" },
    { laber: "河池" },
    { laber: "来宾" },
    { laber: "崇左" },
    { laber: "柳州" },
    ],
    "46": [{ laber: "海口" },
    { laber: "三亚" },
    { laber: "其他" },
    ],
    "50": [{ laber: "万州区" },
    { laber: "涪陵区" },
    { laber: "渝中区" },
    { laber: "大渡口区" },
    { laber: "江北区" },
    { laber: "沙坪坝区" },
    { laber: "九龙坡区" },
    { laber: "南岸区" },
    { laber: "北碚区" },
    { laber: "万盛区" },
    { laber: "双桥区" },
    { laber: "渝北区" },
    { laber: "巴南区" },
    { laber: "黔江区" },
    { laber: "长寿区" },
    { laber: "綦江县" },
    { laber: "潼南县" },
    { laber: "铜梁县" },
    { laber: "大足县" },
    { laber: "荣昌县" },
    { laber: "璧山县" },
    { laber: "梁平县" },
    { laber: "城口县" },
    { laber: "丰都县" },
    { laber: "垫江县" },
    { laber: "武隆县" },
    { laber: "忠县" },
    { laber: "开县" },
    { laber: "云阳县" },
    { laber: "奉节县" },
    { laber: "巫山县" },
    { laber: "巫溪县" },
    { laber: "石柱土家族自治县" },
    { laber: "秀山土家族苗族自治县" },
    { laber: "酉阳土家族苗族自治县" },
    { laber: "彭水苗族土家族自治县" },
    { laber: "江津区" },
    { laber: "合川市" },
    { laber: "永川区" },
    { laber: "南川市" },
    ],
    "51": [{ laber: "成都" },
    { laber: "自贡" },
    { laber: "攀枝花" },
    { laber: "泸州" },
    { laber: "德阳" },
    { laber: "绵阳" },
    { laber: "广元" },
    { laber: "遂宁" },
    { laber: "内江" },
    { laber: "乐山" },
    { laber: "南充" },
    { laber: "眉山" },
    { laber: "宜宾" },
    { laber: "广安" },
    { laber: "达州" },
    { laber: "雅安" },
    { laber: "巴中" },
    { laber: "资阳" },
    { laber: "阿坝" },
    { laber: "甘孜" },
    { laber: "凉山" },
    ],
    "52": [{ laber: "贵阳" },
    { laber: "六盘水" },
    { laber: "遵义" },
    { laber: "安顺" },
    { laber: "铜仁" },
    { laber: "黔西南" },
    { laber: "毕节" },
    { laber: "黔东南" },
    { laber: "黔南" },
    ],
    "53": [{ laber: "昆明" },
    { laber: "曲靖" },
    { laber: "玉溪" },
    { laber: "保山" },
    { laber: "昭通" },
    { laber: "楚雄" },
    { laber: "红河" },
    { laber: "文山" },
    { laber: "思茅" },
    { laber: "西双版纳" },
    { laber: "大理" },
    { laber: "德宏" },
    { laber: "丽江" },
    { laber: "怒江" },
    { laber: "迪庆" },
    { laber: "临沧" },
    ],
    "54": [{ laber: "拉萨" },
    { laber: "昌都" },
    { laber: "山南" },
    { laber: "日喀则" },
    { laber: "那曲" },
    { laber: "阿里" },
    { laber: "林芝" },
    ],
    "61": [{ laber: "西安" },
    { laber: "铜川" },
    { laber: "宝鸡" },
    { laber: "咸阳" },
    { laber: "渭南" },
    { laber: "延安" },
    { laber: "汉中" },
    { laber: "榆林" },
    { laber: "安康" },
    { laber: "商洛" },
    ],
    "62": [{ laber: "兰州市" },
    { laber: "嘉峪关" },
    { laber: "金昌" },
    { laber: "白银" },
    { laber: "天水" },
    { laber: "武威" },
    { laber: "张掖" },
    { laber: "平凉" },
    { laber: "酒泉" },
    { laber: "庆阳" },
    { laber: "定西" },
    { laber: "陇南" },
    { laber: "临夏" },
    { laber: "甘南" },
    ],
    "63": [{ laber: "西宁" },
    { laber: "海东" },
    { laber: "海北" },
    { laber: "黄南" },
    { laber: "海南" },
    { laber: "果洛" },
    { laber: "玉树" },
    { laber: "海西" },
    ],
    "64": [{ laber: "银川" },
    { laber: "石嘴山" },
    { laber: "吴忠" },
    { laber: "固原" },
    { laber: "中卫" },
    ],
    "65": [{ laber: "乌鲁木齐" },
    { laber: "克拉玛依" },
    { laber: "吐鲁番" },
    { laber: "哈密" },
    { laber: "昌吉" },
    { laber: "博尔塔拉" },
    { laber: "巴音郭楞" },
    { laber: "阿克苏" },
    { laber: "克孜勒苏" },
    { laber: "喀什" },
    { laber: "和田" },
    { laber: "伊犁" },
    { laber: "塔城" },
    { laber: "阿勒泰" },
    { laber: "石河子" },
    ],
    "71": [{ laber: "台北市" },
    { laber: "高雄市" },
    { laber: "基隆市" },
    { laber: "台中市" },
    { laber: "台南市" },
    { laber: "新竹市" },
    { laber: "嘉义市" },
    { laber: "台北县" },
    { laber: "宜兰县" },
    { laber: "桃园县" },
    { laber: "新竹县" },
    { laber: "苗栗县" },
    { laber: "台中县" },
    { laber: "彰化县" },
    { laber: "南投县" },
    { laber: "云林县" },
    { laber: "嘉义县" },
    { laber: "台南县" },
    { laber: "高雄县" },
    { laber: "屏东县" },
    { laber: "澎湖县" },
    { laber: "台东县" },
    { laber: "花莲县" },
    ],
    "81": [{ laber: "中西区" },
    { laber: "东区" },
    { laber: "九龙城区" },
    { laber: "观塘区" },
    { laber: "南区" },
    { laber: "深水埗区" },
    { laber: "黄大仙区" },
    { laber: "湾仔区" },
    { laber: "油尖旺区" },
    { laber: "离岛区" },
    { laber: "葵青区" },
    { laber: "北区" },
    { laber: "西贡区" },
    { laber: "沙田区" },
    { laber: "屯门区" },
    { laber: "大埔区" },
    { laber: "荃湾区" },
    { laber: "元朗区" },
    ],
    "82": [{ laber: "花地玛堂区" },
    { laber: "圣安多尼堂区" },
    { laber: "大堂区" },
    { laber: "望德堂区" },
    { laber: "风顺堂区" },
    { laber: "氹仔" },
    { laber: "路环" },
    ]
};


export default city
