var province = [
{id:"44",label:"广东"},
{ id: "11", label: "北京" },
{ id: "33", label: "浙江" },
{ id: "35", label: "福建" },
{ id: "42", label: "湖北" },
{ id: "31", label: "上海" },
{ id: "32", label: "江苏" },
{ id: "12", label: "天津" },
{ id: "13", label: "河北" },
{ id: "14", label: "山西" },
{ id: "15", label: "内蒙古" },
{ id: "21", label: "辽宁" },
{ id: "22", label: "吉林" },
{ id: "23", label: "黑龙江" },
{ id: "34", label: "安徽" },
{ id: "36", label: "江西" },
{ id: "37", label: "山东" },
{ id: "41", label: "河南" },
{ id: "43", label: "湖南" },
{ id: "45", label: "广西" },
{ id: "46", label: "海南" },
{ id: "50", label: "重庆" },
{ id: "51", label: "四川" },
{ id: "52", label: "贵州" },
{ id: "53", label: "云南" },
{ id: "54", label: "西藏" },
{ id: "61", label: "陕西" },
{ id: "62", label: "甘肃" },
{ id: "63", label: "青海" },
{ id: "64", label: "宁夏" },
{ id: "65", label: "新疆" },
{ id: "71", label: "台湾" },
{ id: "81", label: "香港" },
{ id: "82", label: "澳门" },
]
export default province
